export const CREATORS_DATA = [
  {
    id: 'mina-rose',
    name: 'Mina Rose',
    handle: '@minarose_',
    category: 'Làm đẹp & Phong cách sống',
    location: 'Los Angeles, CA',
    verified: true,
    rating: 4.9,
    followers: 1200000,
    engagement: 8.4,
    camps: 42,
    startingPrice: 200,
    priceRange: '$200 - $500',
    platforms: ['IG', 'TT', 'YT'],
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbPXIhrXbW78Yp-vEIloZsqq1hyUq7Xvlj39rWObv_mMc2JnHC_mMWk1eVJy-VhERd56j5oBma0lf4T_tyfD0ZhTeLcxjoZDXjRdocYqmkyYFdGCZsqgnmXoyWwQZ2PlMH7RVzKObjOBDGOtdhU17RjIZt4d3ide9AFY0Tkf1EH3XjM9H2g5xinCOyqeZkVQ5yptL7XAWezBKoW5Tl4dvYV5dUDqoZ9nyGXTm6hYkoenx9nHnleH6ZEIzIbypljRKcjX1U_Fv4ZUo',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUbe3GMSPtWiwGr6ijBNjEODkGVR-iFt5Q2-dQYDTshQxAoPU780edmJSb_Mp-VesGjXQZpLisjt-nb1xw9mdD6U_xaBdFdth3dCbvdUoEtlS6LOBCfddDUAilFpwYPWYe54GdCTvOWwanh4wCBhEK3LiCozfjyMwboSCQc9iaRiHpA88lyYKx1s9DWutUa6o9TqlSeg6UYtF6t5a0qrYnzvSJD3kmcdpHjkE0gBmFlPZbWi71GBKL2Hjitmo25cBKeAxtEbwZWUk',
    bio: 'Đam mê làm đẹp và thời trang bền vững, tôi giúp các thương hiệu kết nối với nhóm khách hàng quan tâm đến tiêu dùng thông minh mà vẫn giữ nguyên tính thẩm mỹ sang trọng. Với hơn 5 năm kinh nghiệm sáng tạo nội dung, cách tiếp cận của tôi là chân thực, trau chuốt về mặt hình ảnh và hướng tới chuyển đổi. Tôi chuyên về trải nghiệm mở hộp, đánh giá trung thực và tích hợp phong cách sống thẩm mỹ.',
    audienceGender: { female: 70, male: 30 },
    audienceAge: [
      { range: '13-17', percentage: 30 },
      { range: '18-24', percentage: 100 },
      { range: '25-34', percentage: 60 },
      { range: '35+', percentage: 20 },
    ],
    pastCampaigns: [
      {
        brand: 'Glow Skincare',
        title: 'Video Ra mắt Mùa hè',
        views: '1.2M',
        type: 'video',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8oJnze5-dKdy4o3_SXo47PtnQjvw2V1mvjtBvEoV9LFhc4LF1TMuzckzhgxN8QFsyAaI9Jz0sg2DjRCA7N8JQ4Spo31NkFw3Va9G9U0EzTwTWUSU4Ac8EY4yP_fsZNLhMdUT0N0bbB4YRhwdVLvnNOLa9AtDsUBS9rDJNbbr5_JnPPEIdFzm2qtgF6nhVsuONeH93dABeBd47gYt3lH1tk8FNboRkXywoRhooWIeRBhYHQ502NgD5ncqxXBzYpL36_qcIB5CzMr0',
      },
      {
        brand: 'Eco Chic',
        title: 'Chuỗi Reel Phối đồ',
        views: '850K',
        type: 'video',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUvhV_aap4DH709vKK82vG9Kw_Ian2rr-XzDX6rT6C2qpbX-F0XXu-Hf5qRzp5nJMECm04WDUIML1mlXH5uCkFsHS8pca6SW73V3hOgY2hGi9F6afgUVupHJp2YqlfKbKxAzrfQMuNRTr0HQAoQM38VMfCfiUIQKMvRJjg6fP_EKHUUXeA0Yf002_7DkG4PaLQuJssxYIOKlT0QyvCxAvwfGMWef-qsDPMEd5Pxe59iQZle-6ru9KfB_oqJ6oehhOt63DHbubFhZE',
      },
      {
        brand: 'Aura Botanica',
        title: 'Chuỗi Carousel Ảnh',
        views: '45K',
        type: 'image',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfbLX0cO2cqpsm05zDn_KgMVLx0-Tr6Qdnu4lOul7zdKhQqtQcGNu8UbkTynSNaHo8wbCPOsJYcr8YlC9mH3SRjOgqDWSChVTkjzTOKtsbGG1rTym11mFOY8bZWFZyK6D4pjHTdBexvk4tuk-4TcHh9qHzZ0bY97tl7Hi7UsMu64k7IQnlZrdQyblm5bDMGkOV5_x89lBQtPo2YGSvjd43CpltLbSSX82msyfhxtGYjxD94VRv9PAnxgbkuV2Hj6-VkijgDhCQb1U',
      },
    ],
    testimonials: [
      {
        brandName: 'Lumina Cosmetics',
        role: 'Giám đốc Marketing',
        rating: 5,
        comment: 'Mina đã mang lại nội dung đặc biệt vượt mục tiêu tương tác của chúng tôi tới 45%. Rất chuyên nghiệp, giao tiếp tốt và sáng tạo!',
        date: '2 tuần trước',
        avatarLetter: 'L',
      },
      {
        brandName: 'Eco Chic Beauty',
        role: 'Điều phối viên PR',
        rating: 4.8,
        comment: 'Làm việc với Mina rất suôn sẻ. Các hướng dẫn thời trang bền vững của cô ấy hoàn toàn phù hợp với tầm nhìn thương hiệu của chúng tôi và tạo được tiếng vang sâu sắc với khán giả.',
        date: '1 tháng trước',
        avatarLetter: 'E',
      },
    ],
  },
  {
    id: 'alex-chen',
    name: 'Alex Chen',
    handle: '@alextech',
    category: 'Công nghệ & Đồ chơi Công nghệ',
    location: 'San Francisco, CA',
    verified: true,
    rating: 4.9,
    followers: 350000,
    engagement: 6.2,
    camps: 18,
    startingPrice: 800,
    priceRange: '$800 - $1200',
    platforms: ['YT', 'TT'],
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrjF2ObrEBxSJqx16u-9oKlZG2JGuud51xCHsq4uUbICYYDWBkgExCqifvoLGA1w57sZe94Ain3M1zogy2I1BvE7R-BKu-d92u495zNMo5M9nM5g_1kpOPyq2UaZG7oyQHZmB6O_nHZk4Q3eh6xn7VfaDTLJS54C55sq9MqCJT22y5uxokCSTlVmwMii8O5FgLZzgt5_aBZEioaMpFlF4OvhAxnnDX8-XQW2fs3n0MSlWK1hOlwCuenz5uPxjVuhdnDDZjlKArUjA',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5niBh9TPMHmHJFWghFkIaOs4BuyEkorF-B1GuHQ8N6KUUqobrbqbOPnnkjeC-DKCWIq_VDEHT3wSM9SdeDVaBiHMSewJPPl_F20QgGfH_DUwePYkV_rJSKv9YZzaJXi0zyDpKWEjoDl6gnRjC5YyVsJJuN5nn5EoeNz6ZeHs-yMw7gb54a40izb1NzcbWSHPyy8LDtPnW7LisVttuz2znfZmUgcx756U5tIgwBt4Um5SjoVq46j2DMSshDbUj3Gdb8Q4lGe_Oau8',
    bio: 'Nhà phân tích công nghệ chuyên sâu và người đánh giá phần cứng tiêu dùng. Cung cấp các thử nghiệm khách quan, chi tiết về các thiết bị thông minh, góc máy setup và các đồ chơi công nghệ tương lai mới nhất.',
    audienceGender: { female: 20, male: 80 },
    audienceAge: [
      { range: '13-17', percentage: 20 },
      { range: '18-24', percentage: 70 },
      { range: '25-34', percentage: 90 },
      { range: '35+', percentage: 40 },
    ],
    pastCampaigns: [
      {
        brand: 'Apex Phone',
        title: 'Video Đánh giá Sản phẩm Chủ lực',
        views: '2.5M',
        type: 'video',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsDLJy7_RTZRBhPgQ5jXd1Hjo6hMRKn18OKQPCvv5dO0IT70QbcpRhQslFqYOg69CWpJZgMgzHpR5suQVT3blICoC161K39od8n3Tp-onF-CnbIBfFv6fGuYbxFZiVpTUbxq4E1FVbgDwrSXrMITDIXmBB3z0Jfv3m5fDSLE1oZ3-xhIPwCHxXe3ZxI3R6xZE7jI9KDjMj-RyS9_dphRGQrNVsXd9Tj4XpEGAh-0g4kJfV58mw_b-B96Xc9ub6jhr0o2R8727iw7U',
      },
    ],
    testimonials: [
      {
        brandName: 'Apex Mobile',
        role: 'Trưởng phòng PR Toàn cầu',
        rating: 5,
        comment: 'Phân tích sản phẩm chi tiết đã trực tiếp mang lại mức tăng doanh số 12% trong tuần lễ ra mắt của chúng tôi. Đầu ra nội dung tuyệt vời.',
        date: '1 tháng trước',
        avatarLetter: 'A',
      },
    ],
  },
  {
    id: 'sarah-jenkins',
    name: 'Sarah Jenkins',
    handle: '@sarahfit',
    category: 'Sức khỏe & Thể hình',
    location: 'New York, NY',
    verified: false,
    rating: 4.7,
    followers: 85000,
    engagement: 8.1,
    camps: 29,
    startingPrice: 150,
    priceRange: '$150 - $300',
    platforms: ['IG'],
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6paWBOpQn2pfuycVtLpJDblv3lzJRf6tWmsAH3PGD6c8VMBVPehbWDRYk1siwth_kVcdOhq6_nvMnFHT97OwbniXZvTFBSomgK21uSgZpc4o1G4D-VeBjuGKyn0zrdFpTIt1UJxanvFAka1Ec23h36QPWTapcK7RDln4o4GB8ibCmPZ4OBsZg9vvkagjJ8n865SH1KiXpB6OrsVlnoY1V4Qm6rRdsSgy0NYe091g9dJifCsKzhqSdtKXBwbLDr8btuCsrvH_ub6g',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUbe3GMSPtWiwGr6ijBNjEODkGVR-iFt5Q2-dQYDTshQxAoPU780edmJSb_Mp-VesGjXQZpLisjt-nb1xw9mdD6U_xaBdFdth3dCbvdUoEtlS6LOBCfddDUAilFpwYPWYe54GdCTvOWwanh4wCBhEK3LiCozfjyMwboSCQc9iaRiHpA88lyYKx1s9DWutUa6o9TqlSeg6UYtF6t5a0qrYnzvSJD3kmcdpHjkE0gBmFlPZbWi71GBKL2Hjitmo25cBKeAxtEbwZWUk',
    bio: 'Huấn luyện viên sức khỏe được cấp chứng nhận, chia sẻ thói quen tập luyện tại nhà hàng ngày, các công thức nấu ăn lành mạnh và lời khuyên thực tế cho sức khỏe và tinh thần minh mẫn.',
    audienceGender: { female: 85, male: 15 },
    audienceAge: [
      { range: '13-17', percentage: 10 },
      { range: '18-24', percentage: 60 },
      { range: '25-34', percentage: 100 },
      { range: '35+', percentage: 50 },
    ],
    pastCampaigns: [
      {
        brand: 'Aura Botanica',
        title: 'Bài đăng Carousel Ảnh',
        views: '45K',
        type: 'image',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfbLX0cO2cqpsm05zDn_KgMVLx0-Tr6Qdnu4lOul7zdKhQqtQcGNu8UbkTynSNaHo8wbCPOsJYcr8YlC9mH3SRjOgqDWSChVTkjzTOKtsbGG1rTym11mFOY8bZWFZyK6D4pjHTdBexvk4tuk-4TcHh9qHzZ0bY97tl7Hi7UsMu64k7IQnlZrdQyblm5bDMGkOV5_x89lBQtPo2YGSvjd43CpltLbSSX82msyfhxtGYjxD94VRv9PAnxgbkuV2Hj6-VkijgDhCQb1U',
      },
    ],
    testimonials: [
      {
        brandName: 'Aura Botanica',
        role: 'Nhà sáng lập',
        rating: 4.8,
        comment: 'Làm việc với Sarah rất dễ chịu. Cô ấy thực sự kết nối với khán giả của mình và giới thiệu các sản phẩm bổ sung sức khỏe của chúng tôi một cách chân thực.',
        date: '3 tuần trước',
        avatarLetter: 'A',
      },
    ],
  },
  {
    id: 'linh-nguyen',
    name: 'Linh Nguyen',
    handle: '@linhstyle_',
    category: 'Thời trang & Phong cách sống',
    location: 'Hà Nội',
    verified: true,
    rating: 4.8,
    followers: 120000,
    engagement: 4.5,
    camps: 42,
    startingPrice: 200,
    priceRange: '$200 - $400',
    platforms: ['IG', 'TT'],
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbIwgIo3emer8702ESbHnfpFGYya02F0dObDjZuWyYmjBxjIijs-PFQhqu0fFpmWADafhqyld5PUYlpb65KHpOChwgO5MnEJ0sxiIZ45vbwZm1reEIggKM-qa17r6WGnn6hDaAh28lE84hjQBCtIBu0EQWLHqhQoWHUw56Siw-U1bXPKmVdPTD0vOSILvMroGm14gHVkWC3lSNZvcNGyWdBQuh58-nHJK0y2fJN73ZHaNSxfHxS_shLtjVwVIhkWS5PW1M2P5zSGc',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDUbe3GMSPtWiwGr6ijBNjEODkGVR-iFt5Q2-dQYDTshQxAoPU780edmJSb_Mp-VesGjXQZpLisjt-nb1xw9mdD6U_xaBdFdth3dCbvdUoEtlS6LOBCfddDUAilFpwYPWYe54GdCTvOWwanh4wCBhEK3LiCozfjyMwboSCQc9iaRiHpA88lyYKx1s9DWutUa6o9TqlSeg6UYtF6t5a0qrYnzvSJD3kmcdpHjkE0gBmFlPZbWi71GBKL2Hjitmo25cBKeAxtEbwZWUk',
    bio: 'Lookbook thẩm mỹ, hướng dẫn thời trang theo mùa và đi cà phê ở Hà Nội. Hợp tác với các thương hiệu thiết kế Việt Nam tinh tế.',
    audienceGender: { female: 80, male: 20 },
    audienceAge: [
      { range: '13-17', percentage: 40 },
      { range: '18-24', percentage: 100 },
      { range: '25-34', percentage: 70 },
      { range: '35+', percentage: 10 },
    ],
    pastCampaigns: [
      {
        brand: 'Glow Skincare',
        title: 'Chuỗi Diện đồ Mùa hè',
        views: '1.2M',
        type: 'video',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8oJnze5-dKdy4o3_SXo47PtnQjvw2V1mvjtBvEoV9LFhc4LF1TMuzckzhgxN8QFsyAaI9Jz0sg2DjRCA7N8JQ4Spo31NkFw3Va9G9U0EzTwTWUSU4Ac8EY4yP_fsZNLhMdUT0N0bbB4YRhwdVLvnNOLa9AtDsUBS9rDJNbbr5_JnPPEIdFzm2qtgF6nhVsuONeH93dABeBd47gYt3lH1tk8FNboRkXywoRhooWIeRBhYHQ502NgD5ncqxXBzYpL36_qcIB5CzMr0',
      },
    ],
    testimonials: [
      {
        brandName: 'Lumina Cosmetics',
        role: 'Quản lý PR',
        rating: 5,
        comment: 'Linh có gu thẩm mỹ tuyệt vời. Các reels hình ảnh của cô ấy đã mang lại lượng truy cập và tương tác khổng lồ cho cửa hàng trực tuyến của chúng tôi.',
        date: '1 tháng trước',
        avatarLetter: 'L',
      },
    ],
  },
  {
    id: 'minh-tran',
    name: 'Minh Tran',
    handle: '@minhtran_reviews',
    category: 'Công nghệ & Đánh giá',
    location: 'TP. Hồ Chí Minh',
    verified: false,
    rating: 4.6,
    followers: 85000,
    engagement: 6.2,
    camps: 18,
    startingPrice: 150,
    priceRange: '$150 - $300',
    platforms: ['TT', 'YT'],
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA2OntZgT8dlWRYW_bv7jFPMrXZJ0hCz14_G6WKOoQgEDQdY3bFGx7gzKhHYaBsadT06MHSrUCA9xNaW4U_Wjv62IRG1-Z2w6BRh-3Qk-oqZZvLhiM8_5n5BUOIUNqoGw1LZp7O4QI6Wjde-zq5AtbpWqW2pY1bPV-VzzB3xPUmKE1oYV6S0oZseAigYFqOv99naHfZivJFaRbCA01acYI5jYN3ODq63TApoljh4T89sW9Mv64-LuAvAYpaz8n22NG2jpyAfreO50k',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC5niBh9TPMHmHJFWghFkIaOs4BuyEkorF-B1GuHQ8N6KUUqobrbqbOPnnkjeC-DKCWIq_VDEHT3wSM9SdeDVaBiHMSewJPPl_F20QgGfH_DUwePYkV_rJSKv9YZzaJXi0zyDpKWEjoDl6gnRjC5YyVsJJuN5nn5EoeNz6ZeHs-yMw7gb54a40izb1NzcbWSHPyy8LDtPnW7LisVttuz2znfZmUgcx756U5tIgwBt4Um5SjoVq46j2DMSshDbUj3Gdb8Q4lGe_Oau8',
    bio: 'Đánh giá công nghệ chân thực, đi thẳng vào vấn đề và so sánh các setup góc máy. Chuyên về bàn phím cơ và công thái học nơi làm việc.',
    audienceGender: { female: 15, male: 85 },
    audienceAge: [
      { range: '13-17', percentage: 25 },
      { range: '18-24', percentage: 95 },
      { range: '25-34', percentage: 80 },
      { range: '35+', percentage: 30 },
    ],
    pastCampaigns: [
      {
        brand: 'MechKeyboards',
        title: 'Chuỗi Đánh giá Chuyên nghiệp',
        views: '110K',
        type: 'video',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsDLJy7_RTZRBhPgQ5jXd1Hjo6hMRKn18OKQPCvv5dO0IT70QbcpRhQslFqYOg69CWpJZgMgzHpR5suQVT3blICoC161K39od8n3Tp-onF-CnbIBfFv6fGuYbxFZiVpTUbxq4E1FVbgDwrSXrMITDIXmBB3z0Jfv3m5fDSLE1oZ3-xhIPwCHxXe3ZxI3R6xZE7jI9KDjMj-RyS9_dphRGQrNVsXd9Tj4XpEGAh-0g4kJfV58mw_b-B96Xc9ub6jhr0o2R8727iw7U',
      },
    ],
    testimonials: [
      {
        brandName: 'MechKeyboards Co',
        role: 'Trưởng bộ phận Vận hành',
        rating: 4.5,
        comment: 'Nội dung chất lượng cao mô tả chi tiết các lợi ích trải nghiệm một cách hoàn hảo. Rất vui với các con số chuyển đổi của mối quan hệ hợp tác này!',
        date: '2 tháng trước',
        avatarLetter: 'M',
      },
    ],
  },
];

export const PACKAGES_DATA = [
  {
    id: 'pro-growth',
    name: 'Gói Tăng trưởng Chuyên nghiệp',
    price: 499,
    billingCycle: '12 Tháng (Thanh toán Hàng tháng)',
    commitment: 'Hợp đồng năm',
    description: 'Giải pháp tất cả trong một tối ưu để mở rộng quy mô thương hiệu của bạn trên TikTok, Instagram và Reels với sự hỗ trợ của chuyên gia. Được thiết kế riêng cho các doanh nghiệp vừa và nhỏ sẵn sàng thống trị các trang mạng xã hội.',
    features: [
      { title: 'Lộ trình Tiếp thị Hỗ trợ bởi AI', desc: 'Chiến lược định hướng dữ liệu tùy chỉnh được tạo riêng cho lĩnh vực thương hiệu của bạn.' },
      { title: '5x Mẫu Nội dung Tùy chỉnh', desc: 'Tài sản sáng tạo được thiết kế thủ công hàng tuần để đạt tỷ lệ tương tác cao.' },
      { title: '2x Chiến dịch KOL do Chúng tôi Quản lý', desc: 'Chúng tôi quản lý việc tiếp cận và thực hiện hai chiến dịch hợp tác với người ảnh hưởng hàng tháng.' },
      { title: 'Ưu tiên Nhân viên Đánh giá', desc: 'Yêu cầu của bạn được xử lý ưu tiên với thời gian phản hồi cam kết trong 24 giờ.' },
      { title: 'Báo cáo Phân tích Hiệu suất Toàn diện', desc: 'Bảng điều khiển thời gian thực theo dõi mức tăng trưởng và ROI của bạn trên tất cả các kênh.' },
      { title: 'Lượt Xuất Dữ liệu Không giới hạn', desc: 'Tải xuống các tài sản và báo cáo độ phân giải cao mà không có giới hạn hàng tháng.' },
    ],
  },
];
